AllCops:
  Include:
    - Gemfile
    - attributes/**/*
    - recipes/**/*
    - libraries/**/*
    - providers/**/*
    - resources/**/*
  Exclude:
    - metadata.rb
    - test/**/*
    - vendor/**/*

Encoding:
  Enabled: false

LineLength:
  Enabled: false

MethodLength:
  Enabled: false

NumericLiterals:
  Enabled: false

HashSyntax:
  Enabled: false

RescueModifier:
  Enabled: false
